version: "3"
services:
  app:
    restart: always
    build: . # Current directory!
    command: "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "3000:8000"
    depends_on:
      - "db"
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=culas58p
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=appadmin
      - MYSQL_PASSWORD=appadmin