# Generated by Django 3.0 on 2019-12-16 18:58

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=75)),
                ('telefone', models.CharField(max_length=25)),
                ('is_staff', models.BooleanField(default=False, help_text='Designa se o usuário pode efetuar login neste administrador.', verbose_name='gerência')),
                ('is_active', models.BooleanField(default=True, help_text='Designa se esse usuário deve ser tratado como ativo. Desmarque isso em vez de excluir contas.', verbose_name='ativo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_inicio', models.DateField(blank=True)),
                ('data_fim', models.DateField(blank=True)),
                ('local', models.CharField(blank=True, max_length=125)),
                ('banner', models.ImageField(default='none-banner.png', upload_to='evento/banner')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=200, populate_from='titulo')),
                ('sobre', models.TextField(blank=True)),
                ('capa', models.ImageField(default='none-capa.png', upload_to='evento/capa')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('afiliacao', models.CharField(blank=True, max_length=45)),
                ('imagem', models.ImageField(default='none-foto.png', upload_to='palestrantes')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigea.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('tipo', models.CharField(max_length=45)),
                ('inscrever', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigea.Evento')),
                ('palestrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sigea.Palestrante')),
            ],
            options={
                'verbose_name_plural': 'Programações',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=125)),
                ('faculdade', models.CharField(blank=True, max_length=50)),
                ('curso', models.CharField(blank=True, max_length=50)),
                ('data_inscricao', models.DateField(auto_now_add=True)),
                ('atividade', models.ManyToManyField(blank=True, to='sigea.Programacao')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigea.Evento')),
            ],
            options={
                'verbose_name_plural': 'Inscricões',
            },
        ),
    ]
