# Generated by Django 2.2.7 on 2019-12-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'customuser', 'verbose_name_plural': 'customusers'},
        ),
    ]
