# Generated by Django 2.2.7 on 2019-12-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigea', '0003_auto_20191201_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'organização', 'verbose_name_plural': 'organizações'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designa se esse usuário deve ser tratado como ativo. Desmarque isso em vez de excluir contas.', verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designa se o usuário pode efetuar login neste administrador.', verbose_name='gerência'),
        ),
    ]
