# Generated by Django 2.2.7 on 2019-12-01 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigea', '0004_auto_20191201_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='imagem',
            field=models.ImageField(default='none.png', upload_to='palestrantes'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=75)),
                ('banner', models.ImageField(upload_to='evento')),
                ('organizacao_idorganizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
