# Generated by Django 2.2.7 on 2019-12-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigea', '0005_auto_20191201_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='apresentacao_capa',
            field=models.ImageField(blank=True, upload_to='evento/capa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='apresentacao_descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='apresentacao_titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, upload_to='evento/banner'),
        ),
    ]
