# Generated by Django 3.0 on 2019-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
