# Generated by Django 3.0 on 2019-12-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigea', '0002_auto_20191216_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(max_length=16),
        ),
    ]
