# Generated by Django 3.0.2 on 2020-01-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigea', '0003_auto_20191216_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(max_length=16),
        ),
    ]
