# Generated by Django 3.0.5 on 2020-04-10 13:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigea', '0005_auto_20200409_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
